local gold = "default:goldblock"
local steel = "default:steelblock"
local diamond = "default:diamondblock"

local alias = {
  {"path6alt:junglewood", "default:junglewood"},
-- remove vines
  {"vines:side_middle", "air"},
  {"vines:side_end", "air"},
  {"vines:root_middle", "air"},
  {"vines:root_end", "air"},
  {"vines:jungle_middle", "air"},
  {"vines:jungle_end", "air"},
  {"vines:vine_middle", "air"},
  {"vines:vine_end", "air"},
  {"vines:willow_middle", "air"},
  {"vines:willow_end", "air"},
-- replace technic machines
  {"technic:lv_electric_furnace", gold},
  {"technic:lv_electric_furnace_active", gold},
  {"technic:mv_electric_furnace", diamond},
  {"technic:mv_electric_furnace_active", diamond},
  {"technic:coal_alloy_furnace", gold},
  {"technic:coal_alloy_furnace_active", gold},
  {"technic:alloy_furnace", gold},
  {"technic:alloy_furnace_active", gold},
  {"technic:mv_alloy_furnace", diamond},
  {"technic:mv_alloy_furnace_active", diamond},
  {"technic:tool_workshop", gold},
  {"technic:grinder", gold},
  {"technic:grinder_active", gold},
  {"technic:mv_grinder", diamond},
  {"technic:mv_grinder_active", diamond},
  {"technic:extractor", gold},
  {"technic:extractor_active", gold},
  {"technic:mv_extractor", diamond},
  {"technic:mv_extractor_active", diamond},
  {"technic:compressor", gold},
  {"technic:compressor_active", gold},
  {"technic:mv_compressor", diamond},
  {"technic:mv_compressor_active", diamond},
  {"technic:cnc", gold},
  {"technic:cnc_active", gold},
  {"technic:mv_centrifuge", diamond},
  {"technic:mv_centrifuge_active", diamond},
-- replace pipeworks nodes
	{"pipeworks:pipe_3_empty", "air"},
	{"pipeworks:autocrafter", gold},
	{"pipeworks:valve_on_empty", steel},
	{"pipeworks:valve_off_empty", steel},
	{"pipeworks:valve_on_loaded", steel},
	{"pipeworks:flow_sensor_empty", steel},
	{"pipeworks:flow_sensor_loaded", steel},
	{"pipeworks:spigot", gold},
	{"pipeworks:spigot_pouring", gold},
	{"pipeworks:entry_panel_empty", gold},
	{"pipeworks:entry_panel_loaded", gold},
	{"pipeworks:grating", gold},
	{"pipeworks:pump_on", gold},
	{"pipeworks:pump_off", gold},
	{"pipeworks:fountainhead", gold},
	{"pipeworks:fountainhead_pouring", gold},
	{"pipeworks:steel_block_embedded_tube", gold},
	{"pipeworks:steel_pane_embedded_tube", gold},
	{"pipeworks:expansion_tank_0", steel},
	{"pipeworks:expansion_tank_1", steel},
	{"pipeworks:expansion_tank_2", steel},
	{"pipeworks:expansion_tank_3", steel},
	{"pipeworks:expansion_tank_4", steel},
	{"pipeworks:expansion_tank_5", steel},
	{"pipeworks:expansion_tank_6", steel},
	{"pipeworks:expansion_tank_7", steel},
	{"pipeworks:expansion_tank_8", steel},
	{"pipeworks:expansion_tank_9", steel},
	{"pipeworks:expansion_tank_10", steel},
	{"pipeworks:storage_tank_0", steel},
	{"pipeworks:storage_tank_1", steel},
	{"pipeworks:storage_tank_2", steel},
	{"pipeworks:storage_tank_3", steel},
	{"pipeworks:storage_tank_4", steel},
	{"pipeworks:storage_tank_5", steel},
	{"pipeworks:storage_tank_6", steel},
	{"pipeworks:storage_tank_7", steel},
	{"pipeworks:storage_tank_8", steel},
	{"pipeworks:storage_tank_9", steel},
	{"pipeworks:storage_tank_10", steel},
	{"pipeworks:trashcan", gold},
}

-- change row[1] into row[2] on map
for _, row in pairs(alias) do
  minetest.register_alias(row[1], row[2])
end
